packages:
  - 'apps/*'
  - 'packages/*'
  - 'services/*'

onlyBuiltDependencies:
  - '@parcel/watcher'
  - core-js
  - ejs
  - yorkie
  - esbuild
  - workerd
  - sharp
  - vue-demi

allowBuilds:
  '@parcel/watcher': true
  core-js: true
  ejs: true
  yorkie: true
  esbuild: true
  workerd: true
  sharp: true
  vue-demi: true
